return {
    diagnostics = {
        disable = {
            "undefined-field",
            "inject-field",
        },
        globals = {
            "COLOR_THEME_ACTIVE",
            "COLOR_THEME_EDIT",
            "COLOR_THEME_FOCUS",
            "COLOR_THEME_PRIMARY1",
            "COLOR_THEME_PRIMARY2",
            "COLOR_THEME_PRIMARY3",
            "COLOR_THEME_SECONDARY1",
            "COLOR_THEME_SECONDARY2",
            "COLOR_THEME_SECONDARY3",
            "COLOR_THEME_WARNING",
            "COLOR_THEME_DISABLED",
            "DBLSIZE",
            "MIDSIZE",
            "MENU_HEADER_HEIGHT",
            "SMLSIZE",
            "STRING",
            "TINSIZE",
            "XXLSIZE",
            "fstat",
            "getFieldInfo",
            "getFlightMode",
            "getGeneralSettings",
            "getRSSI",
            "getTime",
            "getValue",
            "lcd",
            "loadScript",
            "lvgl",
            "model",
        },
    },
}
